FROM alpine:3.18.4

WORKDIR /befunge-build

RUN apk add git make gcc musl-dev
RUN git clone https://github.com/catseye/Befunge-93.git /befunge-build

RUN make

RUN ls bin/bef
RUN cp bin/bef /bin/befunge
RUN cp bin/bef /bin/bef
