jenkins:
  systemMessage: "Welcome to the whanos Jenkins Instance."
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Whanos master"
            permissions:
              - "Overall/Administer"
              - "Global/Read"
              - "Global/Write"
            entries:
              - user: "admin"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
        password: "${ADMIN_USER_PASSWORD}"

jobs:
  - file: "/var/jenkins_home/job_dsl.groovy"

appearance:
  themeManager:
    disableUserThemes: true
    theme: "darkSystem"