name: Publish to Mirror

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-500-TLS-5-1-whanos-matthieu.fraiz.git

jobs:
  publish:
    needs: compile
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url:
          ${{ env.MIRROR_URL }}
        ssh_private_key:
          ${{ secrets.KEY_GIT_PUSH }}

